# These are the supported funding platforms:

github: [jgphilpott] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://www.buymeacoffee.com/jgphilpott"] # Custom sponsorship URLs for Buy Me a Coffee.
