#!/usr/bin/env node

// Example demonstrating enhanced G-code metadata with print statistics
// This example slices various geometries and displays their metadata

const THREE = require('three');
const Polyslice = require('../dist/index.js');
const Printer = require('../src/config/printer/printer.js');
const Filament = require('../src/config/filament/filament.js');

// Helper function to extract metadata from G-code
function extractMetadata(gcode) {
    const lines = gcode.split('\n');
    const metadata = [];
    let inMetadata = false;
    
    for (const line of lines) {
        if (line.startsWith('; Generated by Polyslice')) {
            inMetadata = true;
        }
        if (inMetadata) {
            metadata.push(line);
            if (line.trim() === '' && inMetadata) {
                break;
            }
        }
    }
    
    return metadata.join('\n');
}

// Create test geometries
function createCube(size) {
    const geometry = new THREE.BoxGeometry(size, size, size);
    const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
    return new THREE.Mesh(geometry, material);
}

function createSphere(radius) {
    const geometry = new THREE.SphereGeometry(radius, 32, 32);
    const material = new THREE.MeshBasicMaterial({ color: 0x0000ff });
    return new THREE.Mesh(geometry, material);
}

function createCylinder(radius, height) {
    const geometry = new THREE.CylinderGeometry(radius, radius, height, 32);
    const material = new THREE.MeshBasicMaterial({ color: 0xff0000 });
    return new THREE.Mesh(geometry, material);
}

// Configure slicer with printer and filament for complete metadata
const printer = new Printer('Ender3');
const filament = new Filament('GenericPLA');

const slicer = new Polyslice({
    printer: printer,
    filament: filament,
    metadata: true,
    verbose: false,
    layerHeight: 0.2,
    infillDensity: 20,
    shellWallThickness: 0.8,
    shellSkinThickness: 0.8
});

console.log('='.repeat(80));
console.log('G-CODE METADATA ENHANCEMENT DEMONSTRATION');
console.log('='.repeat(80));
console.log();

// Test 1: Small cube
console.log('TEST 1: Small Cube (10x10x10mm)');
console.log('-'.repeat(80));
const smallCube = createCube(10);
const gcode1 = slicer.slice(smallCube);
console.log(extractMetadata(gcode1));
console.log();

// Test 2: Large cube
console.log('TEST 2: Large Cube (20x20x20mm)');
console.log('-'.repeat(80));
const largeCube = createCube(20);
const gcode2 = slicer.slice(largeCube);
console.log(extractMetadata(gcode2));
console.log();

// Test 3: Sphere
console.log('TEST 3: Sphere (radius 10mm)');
console.log('-'.repeat(80));
const sphere = createSphere(10);
const gcode3 = slicer.slice(sphere);
console.log(extractMetadata(gcode3));
console.log();

// Test 4: Cylinder
console.log('TEST 4: Cylinder (radius 5mm, height 20mm)');
console.log('-'.repeat(80));
const cylinder = createCylinder(5, 20);
const gcode4 = slicer.slice(cylinder);
console.log(extractMetadata(gcode4));
console.log();

// Summary
console.log('='.repeat(80));
console.log('SUMMARY');
console.log('='.repeat(80));
console.log();
console.log('The enhanced metadata now includes:');
console.log('  ✓ Total Layers - Number of layers in the print');
console.log('  ✓ Filament Length - Total filament consumed in mm');
console.log('  ✓ Material Volume - Volume of material in mm³');
console.log('  ✓ Material Weight - Weight of material in grams (when filament specified)');
console.log('  ✓ Estimated Print Time - Formatted as HH:MM:SS');
console.log();
console.log('These statistics help users:');
console.log('  • Estimate material costs');
console.log('  • Plan print schedules');
console.log('  • Track filament usage');
console.log('  • Optimize print settings');
console.log();
