// Generated by CoffeeScript 2.7.0
var Polyslice;

Polyslice = class Polyslice {
  constructor(options = {}) {
    this.gcode = "";
    this.newline = "\n";
    this.autohome = options.autohome != null ? options.autohome : options.autohome = true; // Boolean
    this.workspacePlane = options.workspacePlane != null ? options.workspacePlane : options.workspacePlane = "XY"; // String ['XY', 'XZ', 'YZ']
  }

  getAutohome() {
    return this.autohome;
  }

  getWorkspacePlane() {
    return this.workspacePlane;
  }

  setAutohome(autohome = true) {
    this.autohome = Boolean(autohome);
    return this;
  }

  setWorkspacePlane(plane = "XY") {
    plane = plane.toUpperCase().trim();
    if (["XY", "XZ", "YZ"].includes(plane)) {
      this.workspacePlane = String(plane);
    }
    return this;
  }

  codeAutohome() {
    return "G28" + this.newline;
  }

  codeWorkspacePlane() {
    if (this.getWorkspacePlane() === "XY") {
      return "G17" + this.newline;
    }
    if (this.getWorkspacePlane() === "XZ") {
      return "G18" + this.newline;
    }
    if (this.getWorkspacePlane() === "YZ") {
      return "G19" + this.newline;
    }
  }

  codeMovement(x = null, y = null, z = null, e = null, f = null, s = null) {
    var gcode;
    gcode = "";
    if (typeof x === "number") {
      gcode += " X" + x;
    }
    if (typeof y === "number") {
      gcode += " Y" + y;
    }
    if (typeof z === "number") {
      gcode += " Z" + z;
    }
    if (typeof e === "number") {
      gcode += " E" + e;
    }
    if (typeof f === "number") {
      gcode += " F" + f;
    }
    if (typeof s === "number") {
      gcode += " S" + s;
    }
    return gcode;
  }

  // https://marlinfw.org/docs/gcode/G000-G001.html
  codeLinearMovement(x = null, y = null, z = null, e = null, f = null, s = null) {
    var gcode;
    if (e === null) {
      gcode = "G0";
    } else {
      gcode = "G1";
    }
    gcode += this.codeMovement(x, y, z, e, f, s);
    return gcode + this.newline;
  }

  // https://marlinfw.org/docs/gcode/G002-G003.html
  codeArcMovement(direction = "clockwise", x = null, y = null, z = null, e = null, f = null, s = null, i = null, j = null, r = null, p = null) {
    var gcode;
    if (direction === "clockwise") {
      gcode = "G2";
    } else {
      gcode = "G3";
    }
    if ((i !== null || j !== null) && r === null) {
      gcode += this.codeMovement(x, y, z, e, f, s);
      if (typeof i === "number") {
        gcode += " I" + i;
      }
      if (typeof j === "number") {
        gcode += " J" + j;
      }
      if (typeof p === "number") {
        gcode += " P" + p;
      }
    } else if (i === null && j === null && r !== null && x !== null && y !== null) {
      gcode += this.codeMovement(x, y, z, e, f, s);
      if (typeof r === "number") {
        gcode += " R" + r;
      }
      if (typeof p === "number") {
        gcode += " P" + p;
      }
    } else {
      console.error("Invalid Arc Movement Parameters");
    }
    return gcode + this.newline;
  }

  // https://marlinfw.org/docs/gcode/G005.html
  codeBézierMovement(controlPoints = []) {
    var controlPoint, e, f, gcode, index, k, len, s, x, y;
    gcode = "";
    for (index = k = 0, len = controlPoints.length; k < len; index = ++k) {
      controlPoint = controlPoints[index];
      if (typeof controlPoint.p === "number" && typeof controlPoint.q === "number") {
        if (index === 0 && (typeof controlPoint.i !== "number" || typeof controlPoint.j !== "number")) {
          console.error("Invalid Bézier Movement Parameters");
        } else {
          gcode += "G5";
          x = controlPoint.x;
          y = controlPoint.y;
          e = controlPoint.e;
          f = controlPoint.f;
          s = controlPoint.s;
          gcode += this.codeMovement(x, y, null, e, f, s);
          if (typeof controlPoint.i === "number" && typeof controlPoint.j === "number") {
            gcode += " I" + controlPoint.i;
            gcode += " J" + controlPoint.j;
          }
          gcode += " P" + controlPoint.p;
          gcode += " Q" + controlPoint.q;
          gcode += this.newline;
        }
      } else {
        console.error("Invalid Bézier Movement Parameters");
      }
    }
    return gcode;
  }

  // https://marlinfw.org/docs/gcode/G004.html
  // https://marlinfw.org/docs/gcode/M000-M001.html
  codeDwell(time = null, interruptible = true, message = "") {
    var gcode;
    if (interruptible) {
      gcode = "M0";
    } else {
      gcode = "G4";
    }
    if (typeof time === "number" && time > 0) {
      gcode += " P" + time;
    }
    if (message && typeof message === "string") {
      gcode += " " + message;
    }
    return gcode + this.newline;
  }

  // https://marlinfw.org/docs/gcode/M108.html
  codeInterrupt() {
    return "M108" + this.newline;
  }

  // https://marlinfw.org/docs/gcode/M400.html
  codeWait() {
    return "M400" + this.newline;
  }

  // https://marlinfw.org/docs/gcode/M112.html
  codeShutdown() {
    return "M112" + this.newline;
  }

  slice(scene = {}) {
    if (this.getAutohome()) {
      this.gcode += this.codeAutohome();
    }
    return this.gcode;
  }

};
